import os
import shutil
import yaml

OUTDIR = 'os'
HEADER = '''
# This file has been autogenerated, do not edit!

.macro DEFINE_OS_FUNC name, addr
.globl _\\name
.set _\\name, \\addr
.endm

'''

with open('symbols.yaml', 'rt') as f:
    data = yaml.load(f, yaml.Loader)

osids = {}

try:
    for name, addrs in data['symbols'].items():
        for osid, addr in addrs.items():
            if isinstance(osid, int):
                osid = str(osid)
            ospath = os.path.join(OUTDIR, osid, 'generated')
            if osid not in osids:
                if not os.path.exists(ospath):
                    os.makedirs(ospath)
                fd = open(os.path.join(ospath, 'symbols.S'), 'wt')
                fd.write(HEADER)
                osids[osid] = fd
            if isinstance(addr, int):
                addr = f'0x{addr:08X}'
            osids[osid].write(f'DEFINE_OS_FUNC {name} {addr}\n')
finally:
    for fd in osids.values():
        fd.close()

